// =============================================================================
// FSRMS v2.0 - SERVICE WORKER (sw.js)
// Dikelola oleh VitePWA injectManifest strategy.
// PENTING: Semua `import` WAJIB berada di paling atas file (ES module spec).
// =============================================================================

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';
import {
  openSecureDB,
  getSessionCredentials,
  decryptData,
  sendTelemetry
} from './utils/storageEngine';
import { batchCoalesceMutations } from './utils/syncEngine';

// Global SW Crash Telemetry — harus SETELAH import (ES module spec)
// Menangkap semua unhandled promise rejection di dalam service worker context
self.addEventListener('unhandledrejection', (event) => {
  console.error('SW Unhandled Rejection:', event.reason);
  try {
    sendTelemetry({
      event: 'sw_unhandled_rejection',
      error: event.reason ? String(event.reason) : 'Unknown promise rejection',
      timestamp: new Date().toISOString()
    });
  } catch (_) {
    // Fail silently — telemetry must never cause a secondary crash loop
  }
});

// 1. Precache all static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// 2. FORCE 'NetworkOnly' strategy for dynamic API endpoints
registerRoute(
  ({ url }) => url.pathname.includes('/rest/v1/') || url.pathname.startsWith('/api/v1/'),
  new NetworkOnly()
);

// 3. Intercept navigation requests to leverage preloaded network response (FCP Boost)
registerRoute(
  ({ request }) => request.mode === 'navigate',
  async ({ event }) => {
    try {
      const preloadResponse = await event.preloadResponse;
      if (preloadResponse) {
        return preloadResponse;
      }
      return await fetch(event.request);
    } catch (err) {
      // Offline fallback: serve cached index.html shell
      return (await caches.match('/index.html')) || fetch(event.request);
    }
  }
);

// 4. SW Lifecycle: install + activate with Navigation Preload
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      await self.clients.claim();
      if (self.registration.navigationPreload) {
        await self.registration.navigationPreload.enable();
        console.log('Service Worker: Navigation Preload activated successfully.');
      }
    })()
  );
});

// 5. Native Background Sync event listener
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-transactions') {
    event.waitUntil(
      backgroundSyncFlush()
        .then(() => broadcastToClients({ type: 'BACKGROUND_SYNC_TRIGGER', status: 'success' }))
        .catch((err) => {
          console.error('Service Worker: Background sync flush failed.', err);
          broadcastToClients({ type: 'BACKGROUND_SYNC_TRIGGER', status: 'failure', error: err.message });
        })
    );
  }
});

// 6. Manual sync trigger via postMessage from main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'BACKGROUND_SYNC_TRIGGER') {
    console.log('[SYNC-TRACE][7] SW received BACKGROUND_SYNC_TRIGGER postMessage. Starting backgroundSyncFlush().');
    event.waitUntil(
      backgroundSyncFlush()
        .then(() => {
          console.log('[SYNC-TRACE][11] SW backgroundSyncFlush() completed successfully. Broadcasting to clients.');
          broadcastToClients({ type: 'BACKGROUND_SYNC_TRIGGER', status: 'success' });
        })
        .catch((err) => {
          console.error('[SYNC-TRACE][11] SW backgroundSyncFlush() FAILED:', err.message);
          broadcastToClients({ type: 'BACKGROUND_SYNC_TRIGGER', status: 'failure', error: err.message });
        })
    );
  }
});

// -----------------------------------------------------------------------------
// Utility: Broadcast message ke semua tab aktif
// -----------------------------------------------------------------------------
async function broadcastToClients(message) {
  const clients = await self.clients.matchAll({ type: 'window' });
  for (const client of clients) {
    client.postMessage(message);
  }
}

// -----------------------------------------------------------------------------
// Core: Background sync flusher
// Berjalan sepenuhnya terpisah dari main-thread lifecycle.
// -----------------------------------------------------------------------------
async function backgroundSyncFlush() {
  console.log('[SYNC-TRACE][8] SW backgroundSyncFlush() started.');
  const credentials = await getSessionCredentials();

  // Guard: validasi semua credential sebelum melanjutkan sync
  if (!credentials || !credentials.token) {
    console.warn('[SYNC-TRACE][8a] BREAK POINT: No active auth session credentials. SW sync aborted.');
    return;
  }
  if (!credentials.supabaseUrl) {
    console.error('[SYNC-TRACE][8b] BREAK POINT: supabaseUrl missing. SW sync aborted.');
    return;
  }
  if (!credentials.supabaseAnonKey) {
    console.error('[SYNC-TRACE][8c] BREAK POINT: supabaseAnonKey missing. SW sync aborted.');
    return;
  }

  console.log('[SYNC-TRACE][8d] SW credentials validated. Proceeding to read OFFLINE_MUTATION_QUEUE.');

  const { token, supabaseUrl, supabaseAnonKey } = credentials;
  const db = await openSecureDB();
  const tx = db.transaction('OFFLINE_MUTATION_QUEUE', 'readonly');
  const store = tx.objectStore('OFFLINE_MUTATION_QUEUE');
  const rawItems = await store.getAll();

  if (rawItems.length === 0) {
    console.log('Service Worker Sync: No pending offline mutations to synchronize.');
    return;
  }

  console.log(`[SYNC-TRACE][9] SW found ${rawItems.length} encrypted mutations in queue. Starting per-mutation processing.`);

  let successCount = 0;
  let failCount = 0;
  let lastErrorMsg = '';

  // Step 1: Decrypt all queued items
  const decryptedMutations = [];
  for (const item of rawItems) {
    try {
      const decrypted = await decryptData(item.payload, token);
      decryptedMutations.push({
        queueId: item.id,
        ...decrypted
      });
    } catch (err) {
      console.error(`Service Worker Sync: Decryption failed for queued item #${item.id}. Purging.`, err);
      const secureTx = db.transaction('OFFLINE_MUTATION_QUEUE', 'readwrite');
      await secureTx.objectStore('OFFLINE_MUTATION_QUEUE').delete(item.id);
      failCount++;
      lastErrorMsg = err.message || 'Decryption failed';
    }
  }

  // Step 2: Coalesce mutations to reduce request storms
  const coalescedMutations = batchCoalesceMutations(decryptedMutations);
  console.log(`Service Worker Sync: Coalesced ${decryptedMutations.length} mutations down to ${coalescedMutations.length}`);


  // Step 3: Push each mutation ke Supabase REST API
  for (const mut of coalescedMutations) {
    try {
      let response;

      // Membaca ulang kredensial segar dari IndexedDB sebelum setiap request untuk menghindari race condition
      const freshCredentials = await getSessionCredentials();
      const freshAnonKey = freshCredentials?.supabaseAnonKey || supabaseAnonKey;
      let freshToken = freshCredentials?.token || token;

      // Pastikan token Authorization adalah JWT 3-bagian yang valid.
      // Jika freshToken bernilai mock (1 bagian), ganti dengan freshAnonKey (JWT 3-bagian yang valid)
      if (!freshToken || freshToken.split('.').length !== 3) {
        console.warn('Service Worker Sync: freshToken tidak valid atau format mock (1-part). Menggunakan freshAnonKey untuk Authorization.');
        freshToken = freshAnonKey;
      }

      // Header standar Supabase: apikey (Kong) + Authorization Bearer (PostgREST)
      const headers = {
        'Content-Type': 'application/json',
        'apikey': freshAnonKey,
        'Authorization': `Bearer ${freshToken}`,
        'Prefer': 'return=representation'
      };

      if (mut.type === 'CREATE_CUSTOMER') {
        const custBody = {
          id: mut.payload.id,
          nama_lengkap: mut.payload.name,
          nomor_telepon: mut.payload.phone,
          discount_id: mut.payload.discount_id || null,
          catatan_khusus: mut.payload.notes || null,
          membership_tier: mut.payload.tier || 'Silver',
          total_omset: mut.payload.totalOmset || 0.00,
          total_kunjungan: mut.payload.totalVisits || 1
        };
        console.log('[SYNC-TRACE][10] SW sending CREATE_CUSTOMER to Supabase REST:', JSON.stringify(custBody));
        // Upsert customer baru ke tabel customers
        response = await fetch(`${supabaseUrl}/rest/v1/customers`, {
          method: 'POST',
          headers: {
            ...headers,
            'Prefer': 'resolution=merge-duplicates,return=representation'
          },
          body: JSON.stringify(custBody)
        });
        const respClone = response.clone();
        const respText = await respClone.text().catch(() => '');
        console.log(`[SYNC-TRACE][10a] SW CREATE_CUSTOMER response: status=${response.status} body=${respText.substring(0, 300)}`);

      } else if (mut.type === 'CREATE_APPOINTMENT') {
        const bodyObj = {
          id: mut.payload.id,
          customer_id: mut.payload.customer_id || '00000000-0000-0000-0000-000000000000',
          therapist_id: mut.payload.therapist_id,
          service_id: (mut.payload.service_id && mut.payload.service_id !== '00000000-0000-0000-0000-000000000000') 
            ? mut.payload.service_id 
            : '11111111-1111-1111-1111-111111111111',
          appointment_ts: mut.payload.appointment_ts || mut.payload.date || new Date().toISOString(),
          status: mut.payload.status || 'Scheduled'
        };
        response = await fetch(`${supabaseUrl}/rest/v1/appointments`, {
          method: 'POST',
          headers: {
            ...headers,
            'Prefer': 'resolution=merge-duplicates,return=representation'
          },
          body: JSON.stringify(bodyObj)
        });

        // Instrument response logging
        const responseClone = response.clone();
        const responseText = await responseClone.text().catch(() => '');
        let responseJson = null;
        try { responseJson = JSON.parse(responseText); } catch(e) {}
        console.log('[SUPABASE_DIAGNOSTICS] appointment write: ' + JSON.stringify({
          payload: bodyObj,
          method: 'upsert()',
          requestPath: 'service worker replay',
          response: {
            data: response.ok ? responseJson : null,
            error: !response.ok ? (responseJson || responseText) : null,
            status: response.status,
            statusText: response.statusText
          }
        }));

      } else if (mut.type === 'UPDATE_APPOINTMENT') {
        const bodyObj = {
          status: mut.payload.status
        };
        response = await fetch(`${supabaseUrl}/rest/v1/appointments?id=eq.${mut.payload.id}`, {
          method: 'PATCH',
          headers: {
            ...headers,
            'Prefer': 'return=representation'
          },
          body: JSON.stringify(bodyObj)
        });

        // Instrument response logging
        const responseClone = response.clone();
        const responseText = await responseClone.text().catch(() => '');
        let responseJson = null;
        try { responseJson = JSON.parse(responseText); } catch(e) {}
        console.log('[SUPABASE_DIAGNOSTICS] appointment write: ' + JSON.stringify({
          payload: { id: mut.payload.id, ...bodyObj },
          method: 'update()',
          requestPath: 'service worker replay',
          response: {
            data: response.ok ? responseJson : null,
            error: !response.ok ? (responseJson || responseText) : null,
            status: response.status,
            statusText: response.statusText
          }
        }));

      } else if (mut.type === 'CREATE_SERVICE') {
        // Upsert service baru ke tabel services
        response = await fetch(`${supabaseUrl}/rest/v1/services`, {
          method: 'POST',
          headers: {
            ...headers,
            'Prefer': 'resolution=merge-duplicates,return=representation'
          },
          body: JSON.stringify({
            id: mut.payload.id,
            nama_layanan: mut.payload.nama_layanan,
            kategori: mut.payload.kategori,
            harga_jual: mut.payload.harga_jual,
            description: mut.payload.description || null,
            available_offline: Boolean(mut.payload.available_offline ?? true),
            is_active: Boolean(mut.payload.is_active ?? true)
          })
        });

        if (!response.ok) {
          const errBody = await response.text().catch(() => response.statusText);
          console.error(`Service Worker Sync: CREATE_SERVICE failed on Supabase REST API with status ${response.status}. Error details:`, errBody);
          throw new Error(`Service upsert failed [${response.status}]: ${errBody}`);
        }

      } else if (mut.type === 'CREATE_TRANSACTION' || mut.type === 'UPDATE_TRANSACTION') {
        // FIX: Direct REST upsert ke tabel transactions.
        // RPC upsert_transaction tidak ada di schema — gunakan Prefer: resolution=merge-duplicates
        // agar operasi ini idempoten dan aman untuk retry.
        response = await fetch(`${supabaseUrl}/rest/v1/transactions`, {
          method: 'POST',
          headers: {
            ...headers,
            'Prefer': 'resolution=merge-duplicates,return=representation'
          },
          body: JSON.stringify({
            id: mut.payload.id,
            customer_id: mut.payload.customer_id,
            processed_by: mut.payload.processed_by,
            appointment_id: mut.payload.appointment_id || null,
            discount_id: mut.payload.discount_id || null,
            discount_amount: mut.payload.discount_amount || 0,
            payment_method: mut.payload.payment_method,
            offline_sender: mut.payload.offline_sender || null,
            offline_media: mut.payload.offline_media || null,
            status: mut.payload.status || 'Done',
            total_amount: mut.payload.total_amount,
            created_at: mut.payload.created_at,
            synchronized_at: new Date().toISOString()
          })
        });

        if (!response.ok) {
          const errBody = await response.text().catch(() => response.statusText);
          throw new Error(`Transaction upsert failed [${response.status}]: ${errBody}`);
        }

        // Step B: Upsert cart items ke transaction_items
        if (mut.payload.cart && mut.payload.cart.length > 0) {
          const itemsToInsert = mut.payload.cart.map(item => ({
            transaction_id: mut.payload.id,
            service_id: item.service_id,
            price_at_sale: item.harga_jual
          }));

          const itemResponse = await fetch(`${supabaseUrl}/rest/v1/transaction_items`, {
            method: 'POST',
            headers: {
              ...headers,
              'Prefer': 'resolution=merge-duplicates'
            },
            body: JSON.stringify(itemsToInsert)
          });

          if (!itemResponse.ok) {
            const errBody = await itemResponse.text().catch(() => itemResponse.statusText);
            throw new Error(`Cart items push failed [${itemResponse.status}]: ${errBody}`);
          }
        }
      }

      // Step 4: Tandai sukses — hapus dari queue, update cache status
      if (response) {
        if (response.ok || response.status === 201 || response.status === 200 || response.status === 204) {
          const successTx = db.transaction(['OFFLINE_MUTATION_QUEUE', 'LOCAL_TRANSACTION_CACHE'], 'readwrite');
          const localQueueStore = successTx.objectStore('OFFLINE_MUTATION_QUEUE');
          const localCacheStore = successTx.objectStore('LOCAL_TRANSACTION_CACHE');

          await localQueueStore.delete(mut.queueId);
          const cachedTx = await localCacheStore.get(mut.payload.id);
          if (cachedTx) {
            cachedTx.status = 'Done';
            await localCacheStore.put(cachedTx);
          } else {
            await localCacheStore.put({
              id: mut.payload.id,
              status: 'Done',
              created_at: mut.payload.created_at || new Date().toISOString()
            });
          }
          await successTx.done;
          successCount++;
          console.log(`Service Worker Sync: Successfully synced mutation #${mut.queueId}`);
        } else if (response.status === 409) {
          // Conflict: data sudah ada — anggap sukses, quarantine dari queue
          console.warn(`Service Worker Sync: 409 Conflict for mutation #${mut.queueId}. Quarantining.`);
          const conflictTx = db.transaction('OFFLINE_MUTATION_QUEUE', 'readwrite');
          await conflictTx.objectStore('OFFLINE_MUTATION_QUEUE').delete(mut.queueId);
          await conflictTx.done;
          successCount++;
        } else {
          const errorText = await response.text().catch(() => response.statusText);
          failCount++;
          lastErrorMsg = `SW Server sync error ${response.status}: ${errorText}`;
          
          let postgresCode = '';
          try {
            const jsonErr = JSON.parse(errorText);
            postgresCode = jsonErr.code || '';
          } catch (e) {}

          const isNonTransient = 
            response.status === 400 || 
            response.status === 401 || 
            response.status === 403 || 
            postgresCode === '42501' ||
            postgresCode === 'PGRST204' || 
            postgresCode === '23503' ||
            postgresCode === '22P02' ||
            errorText.toLowerCase().includes('violates foreign key constraint') ||
            errorText.toLowerCase().includes('violates row-level security') ||
            errorText.toLowerCase().includes('in the schema cache');
            
          if (isNonTransient) {
            console.warn(`Service Worker Sync: Non-transient sync failure (${response.status}) for mutation #${mut.queueId}. Isolating.`);
            const quarantineTx = db.transaction(['QUARANTINED_MUTATIONS', 'OFFLINE_MUTATION_QUEUE'], 'readwrite');
            await quarantineTx.objectStore('QUARANTINED_MUTATIONS').put({
              ...mut,
              quarantinedAt: new Date().toISOString(),
              errorLog: errorText
            });
            await quarantineTx.objectStore('OFFLINE_MUTATION_QUEUE').delete(mut.queueId);
            await quarantineTx.done;
          } else {
            throw new Error(`Sync engine transient error [${response.status}]: ${errorText}`);
          }
        }
      }
    } catch (err) {
      failCount++;
      lastErrorMsg = err.message || 'Background sync transport failure';
      console.error(`Service Worker Sync: Failed on mutation #${mut.queueId}. Retrying on next sync.`, err);
      // Preserve FIFO order: hentikan pada kegagalan pertama, retry berikutnya
      break;
    }
  }

  // Kirim telemetry beacon dari background execution
  await sendTelemetry({
    event: 'sync_execution',
    queue_depth: rawItems.length,
    success_count: successCount,
    fail_count: failCount,
    error_message: lastErrorMsg
  });
}
